export const themes = {
  navy: {
    primary: 'navy',
    bgGradient: 'from-navy-700 to-navy-800',
    bgSolid: 'bg-navy-800',
    textAccent: 'text-navy-200',
    textLight: 'text-navy-100',
    bgCard: 'bg-navy-100',
    textCard: 'text-navy-700',
    textHeading: 'text-navy-800',
    bgButton: 'bg-navy-700',
    hoverButton: 'hover:bg-navy-800',
    borderButton: 'border-navy-700',
    bgBadge: 'bg-navy-100',
    textBadge: 'text-navy-700',
    bgCardLight: 'bg-navy-50',
    icon: 'text-navy-600',
    activePagination: 'bg-navy-700 text-white',
    // Add to each theme:
inputFocus: 'focus:border-navy-500 focus:ring-navy-500',
  },
  crimson: {
    primary: 'crimson',
    bgGradient: 'from-crimson-700 to-crimson-800',
    bgSolid: 'bg-crimson-800',
    textAccent: 'text-crimson-200',
    textLight: 'text-crimson-100',
    bgCard: 'bg-crimson-100',
    textCard: 'text-crimson-700',
    textHeading: 'text-crimson-800',
    bgButton: 'bg-crimson-700',
    hoverButton: 'hover:bg-crimson-800',
    borderButton: 'border-crimson-700',
    bgBadge: 'bg-crimson-100',
    textBadge: 'text-crimson-700',
    bgCardLight: 'bg-crimson-50',
    icon: 'text-crimson-600',
    activePagination: 'bg-crimson-700 text-white',
    // Add to each theme:
inputFocus: 'focus:border-navy-500 focus:ring-navy-500',
  },
  brown: {
    primary: 'brown',
    bgGradient: 'from-brown-700 to-brown-800',
    bgSolid: 'bg-brown-800',
    textAccent: 'text-brown-200',
    textLight: 'text-brown-100',
    bgCard: 'bg-brown-100',
    textCard: 'text-brown-700',
    textHeading: 'text-brown-800',
    bgButton: 'bg-brown-700',
    hoverButton: 'hover:bg-brown-800',
    borderButton: 'border-brown-700',
    bgBadge: 'bg-brown-100',
    textBadge: 'text-brown-700',
    bgCardLight: 'bg-brown-50',
    icon: 'text-brown-600',
    activePagination: 'bg-brown-700 text-white',
    // Add to each theme:
inputFocus: 'focus:border-navy-500 focus:ring-navy-500',
  },
  black: {
    primary: 'black',
    bgGradient: 'from-black-700 to-black-800',
    bgSolid: 'bg-black-800',
    textAccent: 'text-black-200',
    textLight: 'text-black-100',
    bgCard: 'bg-black-100',
    textCard: 'text-black-700',
    textHeading: 'text-black-800',
    bgButton: 'bg-black-700',
    hoverButton: 'hover:bg-black-800',
    borderButton: 'border-black-700',
    bgBadge: 'bg-black-100',
    textBadge: 'text-black-700',
    bgCardLight: 'bg-black-50',
    icon: 'text-black-600',
    activePagination: 'bg-black-700 text-white',
    // Add to each theme:
inputFocus: 'focus:border-navy-500 focus:ring-navy-500',
  },
  yellow: {
    primary: 'yellow',
    bgGradient: 'from-yellow-700 to-yellow-800',
    bgSolid: 'bg-yellow-800',
    textAccent: 'text-yellow-200',
    textLight: 'text-yellow-100',
    bgCard: 'bg-yellow-100',
    textCard: 'text-yellow-700',
    textHeading: 'text-yellow-800',
    bgButton: 'bg-yellow-700',
    hoverButton: 'hover:bg-yellow-800',
    borderButton: 'border-yellow-700',
    bgBadge: 'bg-yellow-100',
    textBadge: 'text-yellow-700',
    bgCardLight: 'bg-yellow-50',
    icon: 'text-yellow-600',
    activePagination: 'bg-yellow-700 text-white',
    // Add to each theme:
inputFocus: 'focus:border-navy-500 focus:ring-navy-500',
  },
  green: {
    primary: 'green',
    bgGradient: 'from-green-700 to-green-800',
    bgSolid: 'bg-green-800',
    textAccent: 'text-green-200',
    textLight: 'text-green-100',
    bgCard: 'bg-green-100',
    textCard: 'text-green-700',
    textHeading: 'text-green-800',
    bgButton: 'bg-green-700',
    hoverButton: 'hover:bg-green-800',
    borderButton: 'border-green-700',
    bgBadge: 'bg-green-100',
    textBadge: 'text-green-700',
    bgCardLight: 'bg-green-50',
    icon: 'text-green-600',
    activePagination: 'bg-green-700 text-white',
    // Add to each theme:
inputFocus: 'focus:border-navy-500 focus:ring-navy-500',
  },
  violet: {
    primary: 'violet',
    bgGradient: 'from-violet-700 to-violet-800',
    bgSolid: 'bg-violet-800',
    textAccent: 'text-violet-200',
    textLight: 'text-violet-100',
    bgCard: 'bg-violet-100',
    textCard: 'text-violet-700',
    textHeading: 'text-violet-800',
    bgButton: 'bg-violet-700',
    hoverButton: 'hover:bg-violet-800',
    borderButton: 'border-violet-700',
    bgBadge: 'bg-violet-100',
    textBadge: 'text-violet-700',
    bgCardLight: 'bg-violet-50',
    icon: 'text-violet-600',
    activePagination: 'bg-violet-700 text-white',
    // Add to each theme:
inputFocus: 'focus:border-navy-500 focus:ring-navy-500',
  },
};

export function getTheme(themeName = 'navy') {
  return themes[themeName] || themes.navy;
}
